version: '3'

services:
  db:
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: church_financial
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  church_financial_api:
    restart: always
    build: .
    container_name: church_financial_api
    image: church_financial_api
    environment:
      ENV: dev
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: 12345678
      DJANGO_SUPERUSER_EMAIL: admin@local.com

      SQL_DATABASE: church_financial
      SQL_USER: postgres
      SQL_PASSWORD: postgres
      SQL_HOST: db
      SQL_PORT: 5432

    entrypoint: ["./entrypoint-dev.sh"]
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8080" ]
    volumes:
      - ./:/app
    ports:
      - "9200:8080"
    depends_on:
      - db


volumes:
  postgres_data:
  static_volume:
  media_volume:
