version: '3.3'

services:

  church_sion_financial:
    container_name: church_sion_financial
    image: church_sion_financial
    restart: always
    build: .
    command: npm run dev
    environment:
      NODE_ENV: local
      #GOOGLE_APPLICATION_CREDENTIALS: /service-account.json

      MONGO_PASS: Ljm5aB8h7vOTeDeA
      MONGO_USER: user_sion
      MONGO_DB: dbsionfinancial
      MONGO_SERVER: freesionfinancial.cmomlts.mongodb.net

    volumes:
      - ./:/app
      #- ${GOOGLE_APPLICATION_CREDENTIALS_JASPESOFT}:/service-account.json
      - /home/node/app/node_modules
    ports:
      - "5200:8080"
    networks:
      - church_sion

networks:
  church_sion:
