version: '3.3'

services:

  church_finance_api:
    container_name: church_finance_api
    image: church_finance_api
    restart: always
    build: .
    command: npm run dev
    environment:
      NODE_ENV: local

      MONGO_PASS: Ljm5aB8h7vOTeDeA
      MONGO_USER: user_sion
      MONGO_DB: dbsionfinancial
      MONGO_SERVER: freesionfinancial.cmomlts.mongodb.net

      JWT_SECRET: MG9hNm4xdTFlbGJ6c2a10N7trhjhBwEYj9l7VGDT9e5sc2s4WnEwY2I0dEROeS1uVC1Nd2Rhe7rWG3rfWXX

      TOPIC_ASSIGN_CHURCH: assign_church
      TOPIC_CREATE_USRE_APP: create_user_app
      TOPIC_CHURCH_CREATED: church_created

      AWS_ACCESS_KEY_ID: AKIA4F3QRMUKMAKSD3M5
      AWS_SECRET_ACCESS_KEY: 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
      AWS_REGION: sa-east-1

      BUCKET_FILES: churchs3


    volumes:
      - ./:/app
      #- {GOOGLE_APPLICATION_CREDENTIALS_JASPESOFT}:/service-account.json
      - /home/node/app/node_modules
    ports:
      - "5200:8080"
    networks:
      - church_sion

networks:
  church_sion:
