# Generated by Django 4.2.4 on 2023-08-21 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('registry_number', models.TextField(blank=True, max_length=80, null=True, verbose_name='CNPJ')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='E-mail')),
                ('address', models.TextField(verbose_name='Complemento')),
                ('street', models.TextField(max_length=60, verbose_name='Rua')),
                ('postal_code', models.CharField(max_length=20, verbose_name='CEP')),
                ('opening_date', models.DateField(verbose_name='Data de abertura')),
                ('city', models.CharField(max_length=40, verbose_name='Cidade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='church_country', to='config.country', verbose_name='Pais')),
            ],
            options={
                'verbose_name': 'Igreja',
                'verbose_name_plural': 'Igrejas',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('registry_number', models.TextField(max_length=80, verbose_name='CNPJ')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='district_country', to='config.country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='district_state', to='config.state')),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('dni', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('birthdate', models.DateField(db_index=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('conversion_date', models.DateField()),
                ('baptism_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_church', to='church.church')),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
            },
        ),
        migrations.CreateModel(
            name='Treasurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasurer_church', to='church.church')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='treasurer_member', to='church.member')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='region_district', to='church.district', verbose_name='Distrito')),
            ],
            options={
                'verbose_name': 'Região',
                'verbose_name_plural': 'Regiões',
            },
        ),
        migrations.CreateModel(
            name='Minister',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('dni', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('minister_type', models.CharField(choices=[('REVERED', 'Reverendo'), ('DEACONS', 'Diacono'), ('WORKERS', 'Obrero')], db_index=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='minister_district', to='church.district')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='minister_region', to='church.region')),
            ],
            options={
                'verbose_name': 'Ministro',
                'verbose_name_plural': 'Ministros',
            },
        ),
        migrations.CreateModel(
            name='DistrictLeadership',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('dni', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_districtLeadership', to='church.district')),
            ],
            options={
                'verbose_name': 'Lider del distrito',
                'verbose_name_plural': 'Lideres de distritos',
            },
        ),
        migrations.AddField(
            model_name='church',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='church_district', to='church.district', verbose_name='Regiāo'),
        ),
        migrations.AddField(
            model_name='church',
            name='minister',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='church_minister', to='church.minister', verbose_name='Ministro'),
        ),
        migrations.AddField(
            model_name='church',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='church_region', to='church.region', verbose_name='Regiāo'),
        ),
        migrations.AddField(
            model_name='church',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='church_state', to='config.state', verbose_name='Estado'),
        ),
    ]
