# Generated by Django 4.2.4 on 2023-08-12 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialConcepts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('I', 'INCOME'), ('E', 'DISCHARGE')], max_length=1)),
                ('activated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('destination_movement', models.CharField(choices=[('C', 'PETTY_CASH'), ('E', 'BANK')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_church', to='church.church')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_concept', to='financial.financialconcepts')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('destination_movement', models.CharField(choices=[('C', 'PETTY_CASH'), ('E', 'BANK')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_church', to='church.church')),
            ],
        ),
    ]
