# Generated by Django 4.2.4 on 2023-08-16 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('address_instant_payments', models.CharField(max_length=100, verbose_name='Chave PIX')),
                ('bank_instructions', models.TextField(verbose_name='Instruções para depósitos')),
                ('account_type', models.CharField(choices=[('CC', 'Conta corrente'), ('SC', 'Conta poupança')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_church', to='church.church')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=80, verbose_name='Nome')),
                ('description', models.CharField(max_length=200, verbose_name='Descriçāo')),
                ('type', models.CharField(choices=[('I', 'ENTRADA'), ('E', 'SAIDA')], max_length=1, verbose_name='Tipo')),
                ('activated', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conceito',
                'verbose_name_plural': 'Conceitos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_center_bank', to='financial.bank')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_center_church', to='church.church')),
            ],
            options={
                'verbose_name': 'Centro de custo',
                'verbose_name_plural': 'Centro de custos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MovementBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantia')),
                ('movement_type', models.CharField(choices=[('CREDIT', 'Crédito'), ('DEBIT', 'Débito')], max_length=10, verbose_name='Tipo de movimento')),
                ('description', models.CharField(max_length=180, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_bank_bak', to='financial.bank', verbose_name='Banco')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_bank_church', to='church.church')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantia')),
                ('destination_movement', models.CharField(choices=[('C', 'Em espécie'), ('B', 'Em Banco')], max_length=1, verbose_name='Entrada feita em?')),
                ('observation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observação')),
                ('income_data', models.DateField(verbose_name='Data da entrada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da entrada')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_church', to='church.church', verbose_name='Igreja')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_concept', to='financial.concept', verbose_name='Conceito')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='income_cost_center', to='financial.costcenter', verbose_name='centro de custo')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_data', models.DateField(verbose_name='Data da saida')),
                ('destination_movement', models.CharField(choices=[('C', 'Em espécie'), ('B', 'Em Banco')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_church', to='church.church')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_concept', to='financial.concept')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_cost_center', to='financial.costcenter', verbose_name='centro de custo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiaryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_credit', models.BooleanField(verbose_name='Foi um credito?')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destination_movement', models.CharField(blank=True, choices=[('C', 'Em espécie'), ('B', 'Em Banco')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diary_book_bank', to='financial.bank', verbose_name='Banco')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_book_church', to='church.church')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diary_book_concept', to='financial.concept')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diary_book_cost_center', to='financial.costcenter', verbose_name='centro de custo')),
            ],
            options={
                'verbose_name': 'Livro diario',
                'verbose_name_plural': 'Livro diario',
                'ordering': ['created_at'],
            },
        ),
    ]
